### ISSUE TITLE
Help with phpsms

### ISSUE THREAD

**Issue by funkyfela** [securingsincity/phpsms#1]
Hello. Couldn't find a comprehensive tutorial on how to use phpsms. i want to use it on my web application. can you help with guide? what i tried didnt work.

thank you

**Comment by daluu** [comment]
you probably want to elaborate on what you tried exactly, and what result/response you got from sending the SMS request.

**Comment by securingsincity** [comment]
I would agree with @daluu, @funkyfela an example of what you have so far would help. The README has an example of the usage. If you are not familiar with Composer it is probably best to check out https://getcomposer.org/ and see how to load classes like this library.
